### ISSUE TITLE
Missing Checklists  

### ISSUE THREAD

**Issue by KDrury99** [mitchwinn/elden-ring-cheat-sheet#1]
Hello,

I have been using your elden ring checklist sheet which has been very useful but I have notice that there are missing Checklists for the later areas?

However the checklist total at the top seems to include these missing steps, do you know how to resolve this?

Thanks,

Keaton 
![Screenshot_20230113_090327_com android chrome_edit_100431126312279](https://user-images.githubusercontent.com/122602365/212281812-9fc33dee-d63f-413b-9853-3c794543bf47.jpg)
![Screenshot_20230113_090331_com android chrome_edit_100440012181027](https://user-images.githubusercontent.com/122602365/212281819-a0da1219-702d-4185-b070-f618c8f1d252.jpg)

**Comment by mitchwinn** [comment]
I'll look to update the checklist in the next few days. Thanks for comment!

**Comment by mitchwinn** [comment]
@KDrury99 The missing objectives and incorrect count should be fixed now. Thanks for the issue!
